#index:
#    path: /
#    controller: App\Controller\DefaultController::index
settings_profile:
    path: '/user/settings-profile'
    controller: App\Controller\UserController::goToSettingsProfile
    methods: ['GET']
    defaults:
        form: null
        formImage: null

   

formulaire:
    path: '/user/formulaire'
    controller: App\Controller\UserController::goToFormulaire
    methods: ['GET']

app_front_office:
    path: '/front/index'
    controller: App\Controller\FrontOfficeController::index
    methods: ['GET']